### ISSUE TITLE
Al capturar una fotografía el botón de cancelar cambia de lugar.

### ISSUE THREAD

**Issue by MarioHdpz** [LyticaMx/viasc-app-qa#10]
**Descripción del bug**
Al capturar una fotografía el botón de "Cancelar" está del lado derecho (contrario a las demás áreas de la aplicación) y además es de color verde, lo que hace pensar a los usuarios que es el botón para tomar la foto.
**¿Cómo reproducir?**
Pasos para reproducir:
1. Ir a Iniciar avalúo ->  Capturar de fotos 
2. Observar cómo el botón de Cancelar está del lado izquierdo
3. Dar click en el ícono de fotografía
4. Observar cómo el botón de Cancelar está ahora del lado derecho y es de color verde.

**Comportamiento esperado**
El botón de cancelar debe estar siempre del lado izquierdo y por lo general ser de color rojo.

**Screenshots**
<img src="https://user-images.githubusercontent.com/18600381/71229338-bbdf9c00-22aa-11ea-803f-8d53f4d66b9f.jpg" width="200" />
<img src="https://user-images.githubusercontent.com/18600381/71229367-dd408800-22aa-11ea-9ab4-4cc78b12a18b.jpg" width="200" />

**Dispositivo de prueba:**
 - Dispositivo: Huawei P10 Lite

 - OS: Android
 - Version: 8.0

**Contexto adicional**
N/A

**Comment by HighFlyersDev** [comment]
Resuelto.
