### ISSUE TITLE
Dos manejadores de paquetes en un sólo proyecto

### ISSUE THREAD

**Issue by MarioHdpz** [LyticaMx/viasc-app-qa#22]
**Descripción del bug**
El proyecto cuenta con dos manejadores de paquetes: **npm** y **yarn**, lo cuál puede generar inconsistencias en los **node modules**

**¿Cómo reproducir?**
Pasos para reproducir:
1. Correr *yarn install*
2. Observar la advertencia que manda al inicio de la instalación.

**Comportamiento esperado**
Se debe utilizar un sólo manejador de paquetes.

**Screenshots**
![Screenshot from 2019-12-23 13-44-48](https://user-images.githubusercontent.com/18600381/71377782-4f56ec80-258b-11ea-9c68-5d81746ce39a.png)

![Screenshot from 2019-12-23 13-51-52](https://user-images.githubusercontent.com/18600381/71377844-70b7d880-258b-11ea-91c1-436155a83472.png)

**Dispositivo de prueba:**
n/a
**Contexto adicional**
n/a

**Comment by HighFlyersDev** [comment]
No Aplica:

YARN se debe utilizar de la versión 0.59 de React Native en adelante para instalar librerías en la aplicación. Mientras que NPM, lo utiliza React Native de manera automática a bajo nivel  para el linking de librerías, por ejemplo, para el uso de la cámara.

**Comment by MarioHdpz** [comment]
Entiendo que yarn se debe de utilizar con react native.

Y yarn se conecta al registry de npm (npmjs) para obtener los paquetes, pero eso **no significa que react native use npm**

El hecho de que exista un archivo llamado de **package-lock.json** significa que alguien corrió un **npm install** en el proyecto, cosa que modificó los paquetes que ya se habían instalado con yarn.

Esto podría significar incluso que localmente sus node_modules están ya "tocados" de cierta forma y luego esos ambientes no se pueden reproducir.

Por esa misma razón yarn lanza ese warning.

Yo lo que les sugeriría es que si están utilizando yarn borren el node_modules, el package-lock.json y traten de correr su proyecto con sólo yarn. 

Si les funciona no hay problema, pero si tienen problemas de versiones quiere decir que tienen mezclados los dos manejadores, y el día que otro desarrollador agarre el código va a tener esos mismos problemas.

**Comment by HighFlyersDev** [comment]
se quedo yarn como manejador
