### ISSUE TITLE
Se suben muchos pdf an lugar de uno y a todas las carpetas

### ISSUE THREAD

**Issue by Gibranlytica** [LyticaMx/viasc-app-qa#23]
**Descripción del bug**
Una descripción corta de lo que está sucediendo.

Seleccionas un pdf en tu celular para subir a las carpetas de documentos como escrituras y al seleccionar un archivo .pdf se suben todos los que tengas.

**¿Cómo reproducir?**
Iniciar Avaluo->Adjuntar Documentos-> Escritura-> Subir 
Pasos para reproducir:
1. Ir a 'Iniciar Avaluo'
2. Hacer click en 'Adjuntar Documentos'
3.Subir imagen en formato pdf
4. Observar el error

**Comportamiento esperado**
Solo se debe subir un archivo y no se debe subir a todas las carpetas, sólo a la carpeta que estás parado.

**Screenshots**
Si aplica, agrega screenshots que muestren el problema o bocetos que muestren el resultado esperado.

**Dispositivo de prueba:**
 - Dispositivo: Motorola 5g
 - Andoid: Andoid 
 - Version 7
![WhatsApp Image 2019-12-23 at 1 36 51 PM-1](https://user-images.githubusercontent.com/53920326/71377968-c55b5380-258b-11ea-85e6-274e52837a00.jpeg)
![WhatsApp Image 2019-12-23 at 1 36 51 PM](https://user-images.githubusercontent.com/53920326/71377970-c5f3ea00-258b-11ea-84c8-7d41da87f918.jpeg)

**Comment by HighFlyersDev** [comment]
Mejora:

El acuerdo con Nathalia fue que se podía subir más de un archivo.

**Comment by Gibranlytica** [comment]
Me refiero a que cuando seleccionas un archivo se suben todos los que
tienes y a todas las carpetas.

**Comment by HighFlyersDev** [comment]
Nos pueden proporcionar un video del issue.

Nosotros no pudimos recrear el issue
