### ISSUE TITLE
Se utilizan instrucciones "obsoletas" de gradle

### ISSUE THREAD

**Issue by MarioHdpz** [LyticaMx/viasc-app-qa#25]
**Descripción del bug**
La instrucción **compile** ha sido marcada como obsoleta por gradle, lo que hace a la aplicación vulnerable a fallar en la instalación.

Se marca en la documentación en:
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph

**¿Cómo reproducir?**
Pasos para reproducir:
1. Tratar de generar el release de la aplicación con **./gradlew assembleRelease**
2. Observar los warnings generados.

**Comportamiento esperado**
Se debe evitar usar la instrucción **compile**, gradle sugiere utilizar **implementation**

**Screenshots**
![Screenshot from 2019-12-23 14-04-21](https://user-images.githubusercontent.com/18600381/71378761-95617f80-258e-11ea-8211-805988cc7648.png)

![Screenshot from 2019-12-23 14-12-36](https://user-images.githubusercontent.com/18600381/71378764-97c3d980-258e-11ea-905c-6ceaeef2092c.png)

**Dispositivo de prueba:**
n/a

**Contexto adicional**
n/a

**Comment by HighFlyersDev** [comment]
No aplica:

El 11 de noviembre, fecha de inicio del proyecto, la última versión de React Native que existía era la 0.61.4 el Gradel que se debe utilizar es gradle-5.5-all.zip
La versión del 23 de noviembre (0.61.5) aun no está estable, la comunidad de desarrollo recomienda continuar con la versión 0.61.5 y esperar a la liberación de la versión 0.62.
El cambio de versión de React Native implica al rededor de 20 horas de desarrollo más pruebas.

**Comment by MarioHdpz** [comment]
Hola, el error no se refiera a la versión de Gradle, se refiere a las **instrucciones**.

Se refiere a la instrucción **compile**  que no debe ser utilizada con versiones modernas de gradle, la misma documentación sugiere utilizar **implementetation**

Este bug en particular lo encontramos tratando de correr una herramienta de integración continua, si bien no es algo que afecte el funcionamiento actual del proyecto es algo que en un futuro traerá problemas al tratar de mantener el código.

**Comment by HighFlyersDev** [comment]
Se cambio a implementation
