### ISSUE TITLE
No se respetan la hojas de estilos

### ISSUE THREAD

**Issue by MarioHdpz** [LyticaMx/viasc-app-qa#28]
**Descripción del bug**
Varios componentes declaran una hoja de estilos pero los estilos se agregan **harcodeados** en etiquetas de estilo dentro de los JSXs.

**¿Cómo reproducir?**
Pasos para reproducir:
1. Revisar el archivo el archivo src/components/calendar.js
2. Observar la hoja de estilos declarada en la constante styles (línea 100)
3. Observar uno de los componentes View (línea  78)
4. Observar que tiene los estilos *inline* sobre el componente.

**Comportamiento esperado**
Si se declaran hojas de estilo deben de utilizarse en lugar de los estilos en línea.

**Screenshots**

![Screenshot from 2019-12-23 14-33-37](https://user-images.githubusercontent.com/18600381/71380450-d492cf00-2594-11ea-8366-6dbe68825cbe.png)

![Screenshot from 2019-12-23 14-48-59](https://user-images.githubusercontent.com/18600381/71380452-d65c9280-2594-11ea-8dd6-afc3ddb49979.png)

**Dispositivo de prueba:**
n/a

**Contexto adicional**
n/a

**Comment by HighFlyersDev** [comment]
Resuelto.
