### ISSUE TITLE
Faltan puntos y comas en Javascript

### ISSUE THREAD

**Issue by MarioHdpz** [LyticaMx/viasc-app-qa#29]
**Descripción del bug**
Como buena práctica de Javascript se sugiere poner puntos y comas al final de cada declaración.

**¿Cómo reproducir?**
Pasos para reproducir:
1.  /viascreactnative/App.js

**Comportamiento esperado**
Cada sentencia de javascript debería llevar un punto y coma al final
![Screenshot from 2019-12-23 15-26-11](https://user-images.githubusercontent.com/18600381/71382179-68b46480-259c-11ea-9746-aea3e75e7241.png)

**Screenshots**

**Dispositivo de prueba:**
N/A
**Contexto adicional**
N/A

**Comment by HighFlyersDev** [comment]
Resuelto:

Se eliminaron los puntos y comas. Para JavaScrip 6 no es necesario poner los puntos y comas

**Comment by MarioHdpz** [comment]
Tampoco para ES5, pero se sugiere como buena práctica.

Si un día necesitaran minificar algún código tendrian problemas con eso.
