### ISSUE TITLE
Falta validación de tipo de dato

### ISSUE THREAD

**Issue by haycarlitos** [LyticaMx/viasc-app-qa#3]
**Descripción del bug**
No tiene validación de tipo de dato en los campos "Apellido Materno" y "Delegación".
**¿Cómo reproducir?**
Pasos para reproducir:
1. Iniciar la aplicación.
2. Hacer click en "Iniciar Avalúo" > "Iniciar formulario" > "Datos del solicitante".
3. Llenar con números el campo de "Apellido Materno".
4. Llenar con números el campo de "Delegación".

**Comportamiento esperado**
Debería permitir solo caracteres.

**Screenshots**
![WhatsApp Image 2019-12-19 at 14 15 25](https://user-images.githubusercontent.com/13228328/71206562-71d6c600-226a-11ea-9137-2eb59e86f817.jpeg)

**Dispositivo de prueba:**
 - Dispositivo: Galaxy a7 (2018)
 - OS: Android
 - Version 9
**Contexto adicional**
N/A

**Comment by HighFlyersDev** [comment]
Resuelto.

**Comment by MarioHdpz** [comment]
Se sigue reproduciendo para el campo de apellido Materno.

**Comment by HighFlyersDev** [comment]
Resuelto
