### ISSUE TITLE
Código que no está en uso 

### ISSUE THREAD

**Issue by NestorReal** [LyticaMx/viasc-app-qa#30]
**Descripción del bug**
hay elementos declarados que no son utilizados.
**¿Cómo reproducir?**
Pasos para reproducir:
1. Ir a 'viascreactnative/src/components, 
   viascreactnative/src/containers'
2. Hacer click en 'viascreactnative/src/components, 
   viascreactnative/src/containers'
3. Observar el error

**Comportamiento esperado**
solo dejar declarado elementos que se están utilizando

**Screenshots**
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 14 22 p  m" src="https://user-images.githubusercontent.com/42396321/71382377-50911500-259d-11ea-9825-4a97495bc08a.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 14 18 p  m" src="https://user-images.githubusercontent.com/42396321/71382378-50911500-259d-11ea-85b3-8d2983efc0b6.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 36 p  m" src="https://user-images.githubusercontent.com/42396321/71382379-50911500-259d-11ea-9e52-f3ce478f8f48.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 33 p  m" src="https://user-images.githubusercontent.com/42396321/71382380-50911500-259d-11ea-93c3-9514bcc06857.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 20 p  m" src="https://user-images.githubusercontent.com/42396321/71382381-50911500-259d-11ea-9651-e52e8e3361d7.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 16 p  m" src="https://user-images.githubusercontent.com/42396321/71382382-5129ab80-259d-11ea-86db-536f099e7e0c.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 02 p  m" src="https://user-images.githubusercontent.com/42396321/71382383-5129ab80-259d-11ea-8c1a-c321b215b793.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 12 59 p  m" src="https://user-images.githubusercontent.com/42396321/71382384-5129ab80-259d-11ea-914d-2f2c12060f6f.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 12 24 p  m" src="https://user-images.githubusercontent.com/42396321/71382385-5129ab80-259d-11ea-97bc-8d65ff0763a5.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 12 20 p  m" src="https://user-images.githubusercontent.com/42396321/71382386-5129ab80-259d-11ea-9542-f3b5791d5ee3.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 12 00 p  m" src="https://user-images.githubusercontent.com/42396321/71382387-51c24200-259d-11ea-96b2-e45e6eb16ab6.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 11 54 p  m" src="https://user-images.githubusercontent.com/42396321/71382388-51c24200-259d-11ea-8198-bbf0698d6262.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 14 14 p  m" src="https://user-images.githubusercontent.com/42396321/71382390-51c24200-259d-11ea-9b73-d70b6145ea81.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 14 06 p  m" src="https://user-images.githubusercontent.com/42396321/71382391-51c24200-259d-11ea-9f73-cb2517ee2ef5.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 59 p  m" src="https://user-images.githubusercontent.com/42396321/71382392-51c24200-259d-11ea-840b-e988dfe4891f.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 30 p  m" src="https://user-images.githubusercontent.com/42396321/71382393-51c24200-259d-11ea-85b4-1307ac45142e.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 26 p  m" src="https://user-images.githubusercontent.com/42396321/71382394-525ad880-259d-11ea-840b-a069d6ed8bc6.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 23 p  m" src="https://user-images.githubusercontent.com/42396321/71382396-525ad880-259d-11ea-852c-dd09236ebdb4.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 13 p  m" src="https://user-images.githubusercontent.com/42396321/71382397-525ad880-259d-11ea-8b9b-73794076f620.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 08 p  m" src="https://user-images.githubusercontent.com/42396321/71382398-525ad880-259d-11ea-94dc-d26984b2f60d.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 13 05 p  m" src="https://user-images.githubusercontent.com/42396321/71382399-525ad880-259d-11ea-9356-16a432c7fa7a.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 12 55 p  m" src="https://user-images.githubusercontent.com/42396321/71382400-525ad880-259d-11ea-98f9-13d8816d9917.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 12 33 p  m" src="https://user-images.githubusercontent.com/42396321/71382401-52f36f00-259d-11ea-9d42-2cef25a12472.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 12 28 p  m" src="https://user-images.githubusercontent.com/42396321/71382402-52f36f00-259d-11ea-9e53-663c8ff564e9.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 12 16 p  m" src="https://user-images.githubusercontent.com/42396321/71382403-52f36f00-259d-11ea-9ddb-b23e805a1cb5.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 12 09 p  m" src="https://user-images.githubusercontent.com/42396321/71382404-52f36f00-259d-11ea-9690-6dbe7820ef79.png">
<img width="1679" alt="Captura de Pantalla 2019-12-23 a la(s) 3 12 04 p  m" src="https://user-images.githubusercontent.com/42396321/71382405-52f36f00-259d-11ea-90fb-dd5ae393442b.png">

Si aplica, agrega screenshots que muestren el problema o bocetos que muestren el resultado esperado.

**Contexto adicional**
Si aplica, agrega un contexto adicional sobre la prueba realizada.

**Comment by HighFlyersDev** [comment]
No aplica:

A lo que se refieren es al uso de props. La programación con clases en React Native requiere el uso de props, no podemos quitarlas debido a que causaría warnings durante la ejecución del código.

**Comment by NestorReal** [comment]
No se refiere a las props, es acerca de elementos declarados pero que no se utilizan, por ejemplo

import {
  StyleSheet, Text, View,
  PermissionsAndroid, Platform, Dimensions,
  BackHandler, Alert
} from 'react-native'

aveces no se utiliza (BackHandler o Text) por poner un ejemplo y así hay muchos elementos declarados en los components que no se utilizan, no se refiere a las props. 
Es más que nada por limpieza de código  y buenas practicas.
puedes instalar "VS Code ESLint extension" para que sea más fácil detectar estos detalles

**Comment by HighFlyersDev** [comment]
Se quito el código
