### ISSUE TITLE
Hay bloques de código repetido

### ISSUE THREAD

**Issue by MarioHdpz** [LyticaMx/viasc-app-qa#31]
**Descripción del bug**
Hay componentes donde se repiten bloques idénticos de código, haciendo la aplicación más pesada al final y haciéndola menos legible para otros desarrolladores.

**¿Cómo reproducir?**
Pasos para reproducir:
1. Ver el archivo src/formulario/banios.js
2. Localizar el código dentro de los Selects (220):
```
options = {
    [
         [0,"Liso"],
         [1,"Ladrillo aparente"],
         [2,"Pasta texturizada"],
         [3,"Rústico"],
    ]
 }
```
3. Observar que se repite varias veces

**Comportamiento esperado**
Con el objetivo de hacer la aplicación más ligera y más mantenible hay que evitar repetir bloques de código.

**Screenshots**
![Screenshot from 2019-12-23 15-58-43](https://user-images.githubusercontent.com/18600381/71382482-b7aec980-259d-11ea-9a27-7e7b680c2602.png)
![Screenshot from 2019-12-23 15-58-58](https://user-images.githubusercontent.com/18600381/71382484-baa9ba00-259d-11ea-8498-16aa3ca622c7.png)

**Dispositivo de prueba:**
N/a

**Contexto adicional**
N/a

**Comment by HighFlyersDev** [comment]
No aplica:

En realidad, es necesario repetir el código de las opciones del combobox debido a que hay diferentes secciones que requieren de las mismas opciones de respuesta, por ejemplo en Construcción: mínima, económica, interés social. También para Construcción: medio y semilujo; y para construcción: lujo, residencial y residencial plus.
Por versatilidad del proyecto para realizar ajustes precisos a cada una de las preguntas con el paso del tiempo, recomendamos que se quede así.

**Comment by MarioHdpz** [comment]
Ok, los cerramos con la idea de que en algún momento cambien individualmento los requerimientos para algunos bloqies de código.
