### ISSUE TITLE
Hay herramientas de debuggueo en producción (console.log)

### ISSUE THREAD

**Issue by MarioHdpz** [LyticaMx/viasc-app-qa#34]
**Descripción del bug**
Existe código que está dedicado a desarrollo y se está ejecutando en producción. En particular los console.log no deberían 

**¿Cómo reproducir?**
Pasos para reproducir:
1. Hacer una búsqueda de console.log en el código
2. Observar la cantidad de resultatos
 

**Comportamiento esperado**
Las herramientas de debugueo, como el logueo para debuggear no deberían de correrse en el código de produccción.

**Screenshots**
![Screenshot from 2019-12-23 19-40-08](https://user-images.githubusercontent.com/18600381/71387998-1b47ef80-25bc-11ea-9ffa-1f24f1eb701c.png)

**Dispositivo de prueba:**
N/A

**Contexto adicional**
N/A

**Comment by HighFlyersDev** [comment]
Resuelto:

La aplicación ya está configurada para que el console.log no se muestre en el ambiente de producción. Es posible que ustedes lo continúen viendo porque están en el ambiente de desarrollo. Para que puedan generar la versión de producción pueden consultar los siguientes links:
https://facebook.github.io/react-native/docs/signed-apk-android
https://facebook.github.io/react-native/docs/signed-apk-android#testing-the-release-build-of-your-app

**Comment by MarioHdpz** [comment]
¿Me pueden explicar de qué manera está configurada? 

Según la documentación de React Native no se deben tener console logs, dice que deben de removerse porque puede causar problemas de performance.

https://facebook.github.io/react-native/docs/performance.html#performance

Lo que vi es que si no quieren quitarlos pueden usar un plugin de babel para hacerlo.

![Screenshot from 2020-01-07 10-35-18](https://user-images.githubusercontent.com/18600381/71911591-9d4a2380-3139-11ea-9cfc-c6514f21102a.png)

**Comment by HighFlyersDev** [comment]
Se comentaron la lineas de console.log
