### ISSUE TITLE
El scroll no funciona sobre los campos del formulario

### ISSUE THREAD

**Issue by MarioHdpz** [LyticaMx/viasc-app-qa#4]
**Descripción del bug**
Al intentar hacer scroll sobre los campos del formulario la pantalla no se mueve.

**¿Cómo reproducir?**
Pasos para reproducir:
1. Ir a Iniciar avalúo ->  Iniciar Formulario -> Datos generales -> Datos del solicitante
2. Llenar todo el formulario (El formulario se irá recorriendo hacia abajo)
3. Al terminar, intentar modificar el primer campo de Apellido haciendo un scroll que comienze desde los campos de formularios.
4. El campo sobre el que se hizo el scroll se "mueve un poco", pero la pantalla no se recorre.

**Comportamiento esperado**
Al querer moverme a los campos de hacia arriba para modificarlos se debe poder hacer scroll iniciando desde cualquier parte del formulario.

**Screenshots**
<img src="https://user-images.githubusercontent.com/18600381/71226132-6a321400-22a0-11ea-96c2-f6bd3aff9e2d.jpg" width="200" />

**Dispositivo de prueba:**
 - Dispositivo: Huawei P10 Lite
 - OS: Android
 - Version: 8.0

**Contexto adicional**
N/A

**Comment by CesarNaranjo14** [comment]
Yo también tuve ese problema. Creo sí funciona pero no se tiene que hacer el scroll encima de los campos

**Comment by HighFlyersDev** [comment]
Resuelto.

**Comment by MarioHdpz** [comment]
Hola, se sigue reproduciendo, dejen ver si les puedo mandar un video mejor.

**Comment by HighFlyersDev** [comment]
El scroll se hace del lado derecho de las pantallas

**Comment by MarioHdpz** [comment]
Pendiente de revisar por parte de Lytica
