### ISSUE TITLE
La flecha de regresar no se alcanza a ver bien

### ISSUE THREAD

**Issue by MarioHdpz** [LyticaMx/viasc-app-qa#7]
**Descripción del bug**
Al ingresar a la sección de Adjuntar documentos la flecha de regresar no se ve bien debido al poco contraste que tiene la flecha con el fondo.

**¿Cómo reproducir?**
Pasos para reproducir:
1. Ir a Iniciar avalúo ->  Adjuntar documentos
2. Buscar la flecha de regresar
3. Observar que el contraste entre la flecha y el fondo es muy poco.

**Comportamiento esperado**
La flecha de regresar debe de ser clara, debe contrastar del fondo.

**Screenshots**
![Screenshot_20191219-213007](https://user-images.githubusercontent.com/18600381/71228227-31e20400-22a7-11ea-9cb4-3002fe867bac.jpg)

**Dispositivo de prueba:**
 - Dispositivo: Huawei P10 Lite
 - OS: Android
 - Version: 8.0

**Contexto adicional**
N/A

**Comment by HighFlyersDev** [comment]
Resuelto.
