### ISSUE TITLE
Las flechas de regresar son diferentes en las secciones principales

### ISSUE THREAD

**Issue by MarioHdpz** [LyticaMx/viasc-app-qa#8]
**Descripción del bug**
La flecha de regresar es diferente en secciones principales.

**¿Cómo reproducir?**
Pasos para reproducir:
1. Ir a Iniciar avalúo ->  Iniciar Formulario
2. Observar una flecha de regresar color verde
3. Ir a Iniciar avalúo ->  Adjuntar documentos
4. Observar una flecha de regresar color negra

**Comportamiento esperado**
Las flechas de regresar deben de ser consistentes para una mejor experiencia de usuario.

**Screenshots**
<img src="https://user-images.githubusercontent.com/18600381/71228534-f4ca4180-22a7-11ea-8fa8-661a5c6ce9f7.jpg" width="200" />
<img src="https://user-images.githubusercontent.com/18600381/71228536-f72c9b80-22a7-11ea-8c2f-63bb6b84b637.jpg" width="200" />

**Dispositivo de prueba:**
 - Dispositivo: Huawei P10 Lite
 - OS: Android
 - Version: 8.0

**Contexto adicional**
N/A

**Comment by HighFlyersDev** [comment]
Resuelto.
